### ISSUE TITLE
Error: module.js:538 [read more in]

### ISSUE THREAD

**Issue by hernikplays** [Oliyy/Kahoot-Robot#3]
Happened when launched bot.js with ```node . ```

The Error:
``` 
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Users\root\Desktop\kahoot'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3 ```

**Comment by hernikplays** [comment]
Nvm, just needed to do ```node bot.js ```
